# Generated by Django 5.2.15 on 2026-06-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosfullcars', '0006_estados_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_receptor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='compra',
            name='referencia_entrega',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compra',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
